
version: 2

models:
  - name: customers
    description: "First customers dbt model"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: orders
    description: "Second dbt model"
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null     
      - name: customer_id
        description: "Customer id"
        tests:
        - not_null
        relationships:
          to: ref('customers')
          field: customer_id
